<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Orchard Core Commerce - Shipping Abstractions</Title>
    <Authors>Orchard Core Community and Contributors</Authors>
    <Copyright>Copyright © 2018 .NET Foundation</Copyright>
    <Description>Contains shipping provider interfaces, DTOs, and abstractions for extending OrchardCore Commerce with shipping integrations.</Description>
    <PackageTags>OrchardCore;OrchardCore.Commerce;Shipping;abstraction</PackageTags>
    <RepositoryUrl>https://github.com/OrchardCMS/OrchardCore.Commerce</RepositoryUrl>
    <PackageProjectUrl>https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/src/Libraries/OrchardCore.Commerce.Shipping.Abstractions/Readme.md</PackageProjectUrl>
    <PackageLicenseFile>License.md</PackageLicenseFile>
    <PackageIcon>OrchardCoreIcon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="License.md" Pack="true" PackagePath="" />
    <None Include="Readme.md" />
    <None Include="OrchardCoreIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrchardCore.Commerce.Abstractions\OrchardCore.Commerce.Abstractions.csproj" />
    <ProjectReference Include="..\OrchardCore.Commerce.MoneyDataType\OrchardCore.Commerce.MoneyDataType.csproj" />
  </ItemGroup>

</Project>
