<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Orchard Core Commerce - Shipping - InPost</Title>
    <Authors>Orchard Core Community and Contributors</Authors>
    <Copyright>Copyright © 2018 .NET Foundation</Copyright>
    <Description>InPost shipping provider for Orchard Core Commerce.</Description>
    <PackageTags>OrchardCore;OrchardCore.Commerce;Commerce;e-Commerce;Shipping;InPost</PackageTags>
    <RepositoryUrl>https://github.com/OrchardCMS/OrchardCore.Commerce</RepositoryUrl>
    <PackageProjectUrl>https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/src/Modules/OrchardCore.Commerce.Shipping.InPost/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrchardCore.Commerce.Shipping\OrchardCore.Commerce.Shipping.csproj" />
  </ItemGroup>

</Project>